services:
  - type: web
    name: price-monitor-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: POLL_INTERVAL_SECONDS
        value: "900"
      - key: RATE_LIMIT_MS
        value: "400"
